#!/bin/bash
# Remote Server Troubleshooting Commands
# Usage: ./scripts/troubleshoot-remote.sh

SSH_KEY="$HOME/.ssh/drjjw.pub"
SSH_HOST="root@162.246.254.111"
SSH_PORT="7022"
REMOTE_PATH="/home/docutrainio/public_html"

echo "🔍 Remote Server Troubleshooting Commands"
echo "=========================================="
echo ""
echo "1. Check PM2 status and logs:"
echo "ssh -i $SSH_KEY -p $SSH_PORT $SSH_HOST 'pm2 status && pm2 logs docutrainio-bot --lines 50'"
echo ""
echo "2. Check if server is running:"
echo "ssh -i $SSH_KEY -p $SSH_PORT $SSH_HOST 'curl -s http://localhost:3458/api/health || echo \"Server not responding\"'"
echo ""
echo "3. Check if .env file exists:"
echo "ssh -i $SSH_KEY -p $SSH_PORT $SSH_HOST 'ls -la $REMOTE_PATH/.env || echo \".env file missing!\"'"
echo ""
echo "4. Check server.js for errors:"
echo "ssh -i $SSH_KEY -p $SSH_PORT $SSH_HOST 'cd $REMOTE_PATH && node server.js 2>&1 | head -20'"
echo ""
echo "5. Check port availability:"
echo "ssh -i $SSH_KEY -p $SSH_PORT $SSH_HOST 'netstat -tuln | grep 3458 || echo \"Port 3458 not in use\"'"
echo ""
echo "6. Check recent system logs:"
echo "ssh -i $SSH_KEY -p $SSH_PORT $SSH_HOST 'journalctl -u pm2-root -n 50 --no-pager || dmesg | tail -20'"
echo ""
echo "7. Check disk space:"
echo "ssh -i $SSH_KEY -p $SSH_PORT $SSH_HOST 'df -h'"
echo ""
echo "8. Check Node.js version:"
echo "ssh -i $SSH_KEY -p $SSH_PORT $SSH_HOST 'node --version && npm --version'"
echo ""
echo "9. Check if dependencies are installed:"
echo "ssh -i $SSH_KEY -p $SSH_PORT $SSH_HOST 'cd $REMOTE_PATH && ls -la node_modules | head -5'"
echo ""
echo "10. Restart PM2 process:"
echo "ssh -i $SSH_KEY -p $SSH_PORT $SSH_HOST 'cd $REMOTE_PATH && pm2 restart docutrainio-bot && pm2 logs docutrainio-bot --lines 30'"
echo ""
echo "11. Check file permissions:"
echo "ssh -i $SSH_KEY -p $SSH_PORT $SSH_HOST 'cd $REMOTE_PATH && ls -la server.js package.json && whoami'"
echo ""
echo "12. Monitor PM2 in real-time:"
echo "ssh -i $SSH_KEY -p $SSH_PORT $SSH_HOST 'pm2 monit'"
echo ""
echo "13. Check environment variables (if .env exists):"
echo "ssh -i $SSH_KEY -p $SSH_PORT $SSH_HOST 'cd $REMOTE_PATH && grep -E \"^PORT=|^SUPABASE_URL=\" .env 2>/dev/null || echo \"Cannot read .env\"'"
echo ""
echo "14. Full PM2 information:"
echo "ssh -i $SSH_KEY -p $SSH_PORT $SSH_HOST 'pm2 info docutrainio-bot'"
echo ""
echo "15. Check process memory usage:"
echo "ssh -i $SSH_KEY -p $SSH_PORT $SSH_HOST 'pm2 list && free -h'"
echo ""
echo ""
echo "🚀 Quick Fix Commands:"
echo ""
echo "Copy .env file to remote:"
echo "scp -i $SSH_KEY -P $SSH_PORT .env $SSH_HOST:$REMOTE_PATH/"
echo ""
echo "Full restart:"
echo "ssh -i $SSH_KEY -p $SSH_PORT $SSH_HOST 'cd $REMOTE_PATH && pm2 delete docutrainio-bot && pm2 start server.js --name docutrainio-bot && pm2 save && sleep 3 && pm2 logs docutrainio-bot --lines 20'"
echo ""



